CM-423: added test case for istio-csr
openshift/cert-manager-operator pull request #226
Opened 2024-12-26 05:06 UTC by PillaiManish

2024-12-27 09:55 UTC, swghosh commented
/testwith openshift/cert-manager-operator/master/e2e-operator openshift/cert-manager-operator#220

2025-01-06 12:18 UTC, PillaiManish commented
/reopen

2025-01-07 03:31 UTC, bharath-b-rh commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-01-07 04:31 UTC, TrilokGeer commented on test/e2e/istio_csr_test.go
> +	loader.CreateFromFile(testassets.ReadFile, filepath.Join("testdata", "istio", "istio-subscription.yaml"), "openshift-operators")
Which version is being deployed for service mesh?

2025-01-07 04:31 UTC, TrilokGeer commented on test/e2e/istio_csr_test.go
> +		time.Sleep(2 * time.Second)
It is better to avoid hard coding, use scoped variables or constants enables a single point of change control and better code management.

2025-01-07 04:35 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +	loader.CreateFromFile(testassets.ReadFile, filepath.Join("testdata", "istio", "istio-subscription.yaml"), "openshift-operators")
For service mesh - v2.6.4 is being used.

2025-01-07 04:38 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +		time.Sleep(2 * time.Second)
Okay, will fix that.

2025-01-07 11:58 UTC, swghosh requested changes
Please refactor the tests using a fresh Ginkgo suite that can have a label for `TechPreview:IstioCSR` or the alike.

Also, per discussions with team earlier we can strip the service mesh functionality for now and only make this test, really test the grpc server exposed by istio-csr with a plain client.

2025-01-07 11:58 UTC, swghosh commented on test/library/utils.go
>  func (d DynamicResourceLoader) CreateTestingNS(namespacePrefix string) (*v1.Namespace, error) {
```suggestion
func (d DynamicResourceLoader) CreateTestingNS(namespacePrefix string, shouldGenerateSuffix bool) (*v1.Namespace, error) {
```
consider re-using this function instead of adding another `CreateNS` with necessary `true` or `false` to the later argument.

2025-01-13 10:02 UTC, PillaiManish commented on test/library/utils.go
>  func (d DynamicResourceLoader) CreateTestingNS(namespacePrefix string) (*v1.Namespace, error) {
Fixed and added Ginkgo.

2025-01-13 10:34 UTC, swghosh requested changes
overall the test case(s) seem to be in a good shape.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			By("issuing certificate for TLS")
```suggestion
			By("issuing TLS certificate")
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			By("applying istio issuer")
```suggestion
			By("creating istio-ca issuer")
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			By("applying istio-csr resource")
```suggestion
			By("creating istiocsr.operator.openshift.io resource")
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +									Image: "fullstorydev/grpcurl:latest", // Use your custom image if applicable
```suggestion
									Image: "fullstorydev/grpcurl:latest",
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-issuer.yaml
> +    secretName: root-secret
```suggestion
    secretName: istio-ca
```

If this Issuer intends to use the self-signed CA cert from the other `istio-certificate.yaml`, we need to make the `secretName` reflect correctly.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-issuer.yaml
> +apiVersion: cert-manager.io/v1
to avoid confusion, can we renamed this file to `istio-ca-issuer.yaml`

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-certificate.yaml
> +apiVersion: cert-manager.io/v1
hmm, similarly rename this to `istio-ca-certificate.yaml`.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-certificate.yaml
> +  isCA: true
```suggestion
  selfSigned: {}
  isCA: true
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-certificate.yaml
> +  commonName: istio-ca.my-company.net
```suggestion
  commonName: istio-ca.cluster.local
```

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/istio-certificate.yaml
> +      - my-company.net
```suggestion
      - cluster.local
```

2025-01-13 10:34 UTC, swghosh commented on test/library/utils.go
>  func (d DynamicResourceLoader) CreateTestingNS(namespacePrefix string) (*v1.Namespace, error) {
per my previous comment, please look into adding a `noSuffix` arg to the existing function and reusing it, rather than having to add another new func for the same/similar purpose.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +												Name: "istio-ca-root-cert",
does our istio-csr controller add this ConfigMap?
I couldn't spot any resource for `istio-ca-root-cert` in the `istio-system` namespace. Do you need the service mesh installed + istiod running for this (by any chance)?

Doesn't seem the same as whatever you added in the issuer or certificate yaml(s), so am worried :)

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +
use a util function that has your validations, and call it here.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +
also I don't really think your `commonName` is correct?? where was it added in the CSR to verify.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +
would like to see another validation for cert chain belonging to the right CA.
fine with the other validations for commonName, expiry; apart from keeping them, mainly need to validate as the cert belongs to the CA chain (eg. https://gist.github.com/devtdeng/4f6adcb5a306f2ae035a2e7d9f724d17)

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +func pollTillCompleted(ctx context.Context, clientset *kubernetes.Clientset, namespace, labelSelector string) error {
no need to list the pods and check their status,
just poll the Job object itself and look for it's status to see completion status.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/testdata/istio/proto-cm.yaml
> +  ca.proto: |
can we add a `curl <URL>` for the ca.proto directly inside the Job?

The `<URL>` can be from raw.githubusercontent.com link, **stick the test case to a known good istio api tag** from https://github.com/istio/api/tags (basis of whatever we use in https://github.com/openshift/cert-manager-istio-csr/blob/da02a0a7ce68c0c3fb348a517bec5e68493f31b3/go.mod#L22).

That way we have the expectation during each rebase that if necessary this istio API tag needs to be updated, helps us backtrack if at all the api breaks ever.

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +var _ = Describe("Istio-CSR", Ordered, func() {
```suggestion
var _ = Describe("Istio-CSR", Ordered, Label("TechPreview", "Feature:IstioCSR"), func() {
```
ti's needed for https://github.com/openshift/release/pull/60386

want to trigger the test only when we want to (and `!TechPreview` was not used)...

2025-01-13 10:34 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +	grpcAppName := "grpcurl"
doesn't look relevant here, can you see if it can be moved inside the relevant block?

2025-01-13 14:09 UTC, swghosh commented
/testwith openshift/cert-manager-operator/master/e2e-operator openshift/cert-manager-operator#220

2025-01-13 14:57 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +)
Updated.

2025-01-13 14:58 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +	// Generate a private key
Updated.

2025-01-13 14:58 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +	// Define the CSR template
Updated.

2025-01-13 14:58 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +	// Encode the CSR to PEM format
Updated.

2025-01-13 14:59 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("issuing cluster issuer")
Updated.

2025-01-13 15:00 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +	Context("testing grpc call of istio-csr", Label("Platform: IstioCSR"), func() {
Thanks! Got it and fixed.

2025-01-13 15:00 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("issuing certificate for TLS")
Updated.

2025-01-13 15:06 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +var _ = Describe("Istio-CSR", Ordered, func() {
Added the mentioned labels.

2025-01-13 15:07 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-issuer.yaml
> +apiVersion: cert-manager.io/v1
Renamed the file.

2025-01-15 04:59 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +	escapedCSR := strings.ReplaceAll(string(csrPEM), "\n", "\\n")
It was required to make the JSON payload valid. Else, it was throwing an exception for the new line characters '/n'.

2025-01-15 05:00 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("applying istio issuer")
Updated.

2025-01-15 05:00 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("applying istio-csr resource")
Updated

2025-01-15 05:01 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-certificate.yaml
> +  commonName: istio-ca.my-company.net
Updated.

2025-01-15 05:01 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-certificate.yaml
> +      - my-company.net
Updated.

2025-01-15 05:15 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +									Image: "fullstorydev/grpcurl:latest", // Use your custom image if applicable
Fixed.

2025-01-15 06:17 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +
Added function in utility for validations.

2025-01-15 06:22 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +												Name: "istio-ca-root-cert",
Nvm, my bad. The istio-csr agent itself copies that config map to each namespace on the cluster. But I think we could poll for that config map to be created first, the Job's Pod stay in ContainerCreating state for a long time until that config map is made available for mounting as a volume.

2025-01-15 06:48 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +	escapedCSR := strings.ReplaceAll(string(csrPEM), "\n", "\\n")
din't mean to suggest to remove this line of code,
what I meant was to add a comment  why this is being done,
it's fine even without.

2025-01-15 06:48 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			tokenResponse, err := clientset.CoreV1().ServiceAccounts("istio-system").CreateToken(ctx, serviceAccountName, tokenRequest, metav1.CreateOptions{})
we should remove this call from here, it hardcodes the token into the deployment yaml as a result of fetching it previously + we risk the chance that the token being used inside the pod can be expired.

Instead, can use: `pod.spec.volumes.projected.sources.serviceAccountToken.audience` with "istio-ca" and mount a volume on the Job's Pod spec which should take care of this JWT. Also, for it to work the grpcurl pod should use `serviceAccountName: cert-manager-istio-csr`.

2025-01-15 06:48 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			tokenResponse, err := clientset.CoreV1().ServiceAccounts("istio-system").CreateToken(ctx, serviceAccountName, tokenRequest, metav1.CreateOptions{})
ref: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api

2025-01-15 08:24 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-certificate.yaml
> +  isCA: true
This file was redundant, and is deleted now.

2025-01-17 08:18 UTC, bharath-b-rh commented on test/e2e/istio-csr_test.go
> +									Args: []string{
Which certificate is used for gRPC client? I think it would be better to make use of certificate created by the controller for istio. Certificate is created in configured istio's namespace, with the name `istiod`. And required dnsNames to be added to certificate can also be configured.

2025-01-17 08:18 UTC, bharath-b-rh commented on test/e2e/istio-csr_test.go
> +										fmt.Sprintf("cert-manager-istio-csr.%s.svc:443", ns.Name),
Please use `status.istioCSRGRPCEndpoint` from `istiocsr` resource, which will help in validating correct value is set.

2025-01-17 08:22 UTC, bharath-b-rh commented
Please add the description.

2025-01-17 09:16 UTC, PillaiManish commented on test/e2e/testdata/istio/proto-cm.yaml
> +  ca.proto: |
Added the same to fetch the proto file directly from istio/api repo.

2025-01-19 13:24 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +										fmt.Sprintf("cert-manager-istio-csr.%s.svc:443", ns.Name),
Updated.

2025-01-20 14:08 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +									Args: []string{
Yes, fixed the code and using the istiod-tls for certificate & private key.

2025-01-21 05:39 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("poll till the service account is available")
Updated according to the comment.

2025-01-21 14:46 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-certificate.yaml
> +apiVersion: cert-manager.io/v1
This file is now deleted.

2025-01-21 14:51 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-certificate.yaml
> +  commonName: istio-ca.my-company.net
This file is now deleted.

2025-01-21 14:56 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			tokenResponse, err := clientset.CoreV1().ServiceAccounts("istio-system").CreateToken(ctx, serviceAccountName, tokenRequest, metav1.CreateOptions{})
Updated.

2025-01-21 14:58 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-issuer.yaml
> +    secretName: root-secret
The issuer  will be using the certificate signed by the cluster-issuer.

2025-01-21 16:56 UTC, PillaiManish commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-01-24 11:14 UTC, PillaiManish commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-01-29 15:46 UTC, bharath-b-rh commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-01-30 19:25 UTC, swghosh commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-01-30 20:00 UTC, swghosh commented on test/e2e/utils_test.go
> +		}
please parse the status.conditions into a metav1.Condition, and use the https://pkg.go.dev/k8s.io/apimachinery/pkg/api/meta#FindStatusCondition helper func instead.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/utils_test.go
> +		customResource, err := dynamicClient.Resource(gvr).Namespace(namespace).Get(ctx, istioCsrName, metav1.GetOptions{})
while not completely opposing use of the dynamic resource client,
see if it is convenient to use a istiocsr client directly from `"github.com/cert-manager/cert-manager/pkg/client/clientset/versioned"`

eg.
https://github.com/openshift/cert-manager-operator/blob/6fbe83159f4b7b5f886462c0b198242b4c3b1711/test/e2e/utils_test.go#L19

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +//go:build e2e
please rename this file to `istio_csr_test.go`.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			istioURL := "https://raw.githubusercontent.com/istio/api/v1.24.1/security/v1alpha1/ca.proto"
use as a `const` for this near the top of this file.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +											fmt.Sprintf("-d '{\"csr\": \"%s\", \"validity_duration\": 3600}' ", csr) +
nit(improves readability): store this in a new variable above, then use it here.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +											fmt.Sprintf("%s istio.v1.auth.IstioCertificateService/CreateCertificate", istioCSRGRPCEndpoint),
nit(improves readability): store this in a another new variable above, then use it here.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +				}
since these are Pods from a Job, under some circumstance we might see a pod that had failed, the Job would retry in that case.

Hence, make this loop such that we can get a "atleast once" guarantee. Also, ignore errors otherwise.

2025-01-30 20:00 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +			By("reading logs of the grpcurl job")
```suggestion
```

redundant.

2025-01-31 09:19 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			By("reading logs of the grpcurl job")
Updated.

2025-01-31 10:32 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +//go:build e2e
Updated.

2025-01-31 10:41 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +			istioURL := "https://raw.githubusercontent.com/istio/api/v1.24.1/security/v1alpha1/ca.proto"
Fixed.

2025-01-31 10:57 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +				}
For retry, there should be retry attempt or time limit?

2025-02-03 11:25 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +				}
set `.spec.completions = 1` and `.spec.backoffLimit = N`, N can be a reasonable retry limit like 10. 

https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures

2025-02-03 11:39 UTC, swghosh commented on test/e2e/istio-csr_test.go
> +				}
Filter out the pod loop by looking only into pods with status Completed.


what I mean is:
```

desiredPodName := ""
for _, pod := range pods.Items {
    if pod.Status.Phase == "Succeeded" {
            desiredPodName = pod.Name
    }
}

Expect(desiredPodName).ShouldNot(BeEmpty())


req := clientset.CoreV1().Pods(ns.Name).GetLogs(desiredPodName, &corev1.PodLogOptions{})
// ...
```

2025-02-03 12:58 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +				}
Done.

2025-02-03 13:00 UTC, PillaiManish commented on test/e2e/istio-csr_test.go
> +											fmt.Sprintf("%s istio.v1.auth.IstioCertificateService/CreateCertificate", istioCSRGRPCEndpoint),
Updated

2025-02-04 15:03 UTC, swghosh commented
/label docs-approved
/label px-approved
No user facing changes, this is essentially a follow-up over #220.

2025-02-07 14:26 UTC, bharath-b-rh commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-02-11 14:07 UTC, bharath-b-rh commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-02-12 08:15 UTC, lunarwhite commented
/testwith openshift/cert-manager-operator/master/e2e-operator #220

2025-02-12 08:17 UTC, lunarwhite commented
/testwith openshift/cert-manager-operator/master/e2e-operator https://github.com/openshift/cert-manager-operator/pull/220

2025-02-12 14:17 UTC, swghosh commented
/test all

2025-02-12 14:17 UTC, swghosh commented
/cherry-pick cert-manager-1.15

2025-02-13 06:15 UTC, bharath-b-rh commented
/lgtm

2025-02-13 07:57 UTC, lunarwhite commented
/assign

2025-02-13 09:50 UTC, lunarwhite commented on test/library/utils.go
> +	}
Could we decouple the hardcoded template from this func?

2025-02-13 09:50 UTC, lunarwhite commented on test/e2e/istio_csr_test.go
> +const ISTIO_CSR_URL = "https://raw.githubusercontent.com/istio/api/v1.24.1/security/v1alpha1/ca.proto"
It would be great if we could add a comment for each constant.

2025-02-13 09:50 UTC, lunarwhite commented on test/e2e/utils_test.go
> +		return sa != nil, nil
```suggestion
		return true, nil
```

2025-02-13 12:11 UTC, PillaiManish commented on test/e2e/utils_test.go
> +		return sa != nil, nil
Updated.

2025-02-13 12:12 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +			Expect(err).Should(BeNil())
Updated

2025-02-14 10:49 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +const ISTIO_CSR_URL = "https://raw.githubusercontent.com/istio/api/v1.24.1/security/v1alpha1/ca.proto"
Done.

2025-02-14 19:35 UTC, swghosh commented on test/e2e/utils_test.go
> +		sa, err := clientset.CoreV1().ServiceAccounts(namespace).Get(ctx, serviceAccountName, metav1.GetOptions{})
```suggestion
		_, err := clientset.CoreV1().ServiceAccounts(namespace).Get(ctx, serviceAccountName, metav1.GetOptions{})
```

unused variable,
needed to make sure the e2e can build and run.

2025-02-17 09:57 UTC, PillaiManish commented on test/e2e/utils_test.go
> +		sa, err := clientset.CoreV1().ServiceAccounts(namespace).Get(ctx, serviceAccountName, metav1.GetOptions{})
Thanks, fixed.

2025-02-20 08:06 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +			}
prefer a file for this instead, as most of the field values are fixed. `replaceStrInFile` can help;
however follow-up PR is fine.

2025-02-25 05:36 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +const istio_csr_url = "https://raw.githubusercontent.com/istio/api/v1.24.1/security/v1alpha1/ca.proto"
Fixed.

2025-02-25 05:44 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +			}
Maybe I can do it in a follow-up, if that works?

2025-02-25 05:45 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +			}
let's de-clutter it, how about a `test/e2e/testdata/istio_csr/grpcurl_job.yaml`?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: grpcurl-istio-csr
spec:
  backoffLimit: 10
  completions: 1
  template:
    metadata:
      labels:
        app: grpcurl-istio-csr
      name: grpcurl-istio-csr
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - |
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v1.9.2 >/dev/null 2>&1 && \
          TOKEN=$(cat /var/run/secrets/istio-ca/token) && \
          /tmp/go/bin/grpcurl \
            -import-path /proto \
            -proto /proto/ca.proto \
            -H "Authorization: Bearer $TOKEN" \
            -d '{"csr": "{{.CertificateSigningRequest}}", "validity_duration": 3600}' \
            -cacert /etc/root-secret/ca.crt \
            -key /etc/root-secret/tls.key \
            -cert /etc/root-secret/tls.crt \
            {{.IstioCSRStatus.IstioCSRGRPCEndpoint}} istio.v1.auth.IstioCertificateService/CreateCertificate
        command:
        - /bin/sh
        - -c
        env:
        - name: GOCACHE
          value: /tmp/go-cache
        - name: GOPATH
          value: /tmp/go
        image: registry.redhat.io/rhel9/go-toolset
        name: grpcurl
        volumeMounts:
        - mountPath: /etc/root-secret
          name: root-secret
        - mountPath: /proto
          name: proto
        - mountPath: /var/run/secrets/istio-ca
          name: sa-token
      restartPolicy: OnFailure
      serviceAccountName: '{{.IstioCSRStatus.ServiceAccount}}'
      volumes:
      - name: sa-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 3600
              path: token
      - name: root-secret
        secret:
          secretName: istiod-tls
      - configMap:
          name: proto-cm
        name: proto
```

what I meant basically pushes ahead of https://github.com/openshift/cert-manager-operator/pull/247, so that within `test/e2e/config_template.go` we can add:
```diff
+ // IstioCSRConfig customizes the fields in a job spec
+ type IstioCSRGRPCurlJobConfig struct {
+ 	CertificateSigningRequest string
+ 	IstioCSRStatus            v1alpha1.IstioCSRStatus
+ }
```
to get the above yaml value filled in during test.

2025-02-25 06:18 UTC, swghosh approved these changes
few nits, otherwise LGTM.

2025-02-25 06:18 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +									Name: "service-token",
```suggestion
									Name: "sa-token",
```

2025-02-25 06:18 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +											"export GOPATH=/tmp/go && " +
please move `GOCACHE` and `GOPATH` into the env stanza instead.

2025-02-25 06:18 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +										{Name: "service-token", MountPath: "/var/run/secrets/istio-ca"},
```suggestion
										{Name: "sa-token", MountPath: "/var/run/secrets/istio-ca"},
```

2025-02-25 06:18 UTC, swghosh commented on test/e2e/testdata/istio/istio-ca-issuer.yaml
rename: `istio_ca_issuer.yaml`

2025-02-25 06:18 UTC, swghosh commented on test/e2e/testdata/istio/istio-csr.yaml
rename: `istio_csr.yaml`

2025-02-25 06:19 UTC, swghosh commented on test/e2e/istio_csr_test.go
> +			}
As discussed, we'll do this on a follow-up PR after #247 lands.

2025-02-25 06:34 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +										{Name: "service-token", MountPath: "/var/run/secrets/istio-ca"},
Updated.

2025-02-25 06:35 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-ca-issuer.yaml
Fixed.

2025-02-25 06:35 UTC, PillaiManish commented on test/e2e/testdata/istio/istio-csr.yaml
Fixed.

2025-02-25 06:36 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +									Name: "service-token",
Fixed.

2025-02-25 07:11 UTC, swghosh commented
/retitle CM-423: Adds e2e test for istio-csr controller with grpc CreateCertificate call

2025-02-25 08:32 UTC, lunarwhite reviewed
LGTM, only minor nits

2025-02-25 08:32 UTC, lunarwhite commented on test/e2e/istio_csr_test.go
> +			Expect(err).Should(BeNil())
```suggestion
			Expect(err).Should(BeNil())
			Expect(entry.CertChain).ShouldNot(BeEmpty())
```
adding a checkpoint to ensure the chain is not empty, otherwise the for loop won't execute

2025-02-25 09:40 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +				if pod.Status.Phase == "Succeeded" {
Fixed.

2025-02-25 09:40 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +	ctx := context.Background()
Fixed

2025-02-25 09:41 UTC, PillaiManish commented on test/e2e/istio_csr_test.go
> +			Expect(err).Should(BeNil())
Updated

2025-02-25 10:22 UTC, lunarwhite commented
/label qe-approved
/lgtm

2025-02-25 13:20 UTC, swghosh commented
/cherry-pick cert-manager-1.15

2025-02-25 14:54 UTC, merged